services:
  terminal-server:
    build:
      context: .
    container_name: python_gateway
    restart: always
    environment:
      PROJECT_PATH: ${PROJECT_PATH:-/app}
    ports:
      - "51234:51234"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./logs:/var/log/terminal-server
      - .:/app
    networks:
      - lab-net

  admin-panel:
    build: .
    container_name: admin_panel
    command: python3 admin_panel.py
    ports:
      - "5001:5001"
    volumes:
      - .:/app
      - ./logs:/var/log/terminal-server
    networks:
      - lab-net

networks:
  lab-net:
    name: lab-net